version: '3'
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inmobiliaria
    ports:
      - "3306:3306"  
    networks:
      - mynetwork
  springbootapp:
    image: blasdsaidon/fincas.litoral:v1.2
    container_name: springboot-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inmobiliaria?allowPublicKeyRetrieval=true&useSSL=FALSE&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - /Users/juliavallejos/Documents/fincas-litoral/mysqlDB:/var/lib/mysql
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
